services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
        expose:
            - 27017
        ports:
            - 27017:27017
        volumes:
            - db-data:/data/db
            - db-data:/data/configdb

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8080:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: user
            ME_CONFIG_BASICAUTH_PASSWORD: pass
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
        volumes:
            - db-data:/data
            
    # nodejs:
    #     image: node:16
    #     restart: always
    #     volumes:
    #         - ./:/app
    #     ports:
    #         - 80:3000
    #     working_dir: /app
    #     command: npm run dev
volumes:
    db-data: